/* Cyber-Us dynamic reader: published episodes only. */
(()=>{'use strict';
const target=document.querySelector('#dynamicComicCatalog, #comicDynamicContent');if(!target)return;
const db=window.CyberUsGetClient?.();
const add=(tag,value,parent)=>{const el=document.createElement(tag);if(value!==null)el.textContent=value;parent.append(el);return el};
const params=new URLSearchParams(location.search);
const lang=params.get('lang')==='en'?'en':params.get('lang')==='pt'?'pt':(localStorage.getItem('cyber-us-language')==='en'?'en':'pt');
async function records(){const {data,error}=await db.from('comic_publications').select('id,chapter_number,episode_number,language_code,title,author_note,page_paths,status,publish_at,legacy_slug').eq('language_code',lang).order('chapter_number').order('episode_number');if(error)throw error;return(data||[]).filter(p=>(p.status==='published'||(p.status==='scheduled'&&p.publish_at&&Date.parse(p.publish_at)<=Date.now()))&&p.page_paths?.length)}
async function run(){if(!db){target.textContent='Serviço indisponível.';return}try{const rows=await records();target.replaceChildren();if(target.id==='dynamicComicCatalog'){for(const p of rows.filter(p=>!p.legacy_slug)){const a=add('a','Cp-'+p.chapter_number+' ep-'+p.episode_number+' · '+p.title+' →',target);a.href='leitor-dinamico.html?chapter='+p.chapter_number+'&episode='+p.episode_number+'&lang='+lang;a.style.cssText='display:block;padding:12px;border-bottom:1px solid #596477'}if(!rows.length)add('p',lang==='pt'?'Nenhum novo episódio.':'No new episodes yet.',target);return}const ch=Number(params.get('chapter')),ep=Number(params.get('episode'));if(!Number.isSafeInteger(ch)||!Number.isSafeInteger(ep)||ch<0||ep<0)throw Error('Identificador inválido');const p=rows.find(x=>x.chapter_number===ch&&x.episode_number===ep);if(!p){add('p','Episódio não disponível.',target);return}document.title='Cyber-Us · '+p.title;add('h1',p.title,target);for(const path of p.page_paths){const {data,error}=await db.storage.from('comic-pages').createSignedUrl(path,300);if(error||!data?.signedUrl){add('p','Não foi possível carregar a imagem.',target);continue}const img=add('img',null,target);img.src=data.signedUrl;img.alt=p.title;img.loading='lazy';img.style.cssText='display:block;width:100%;max-width:900px;height:auto;margin:0 auto'}if(p.author_note){const section=add('section',null,target);section.className='creator-card';add('h2',lang==='pt'?'Nota do autor':'Author note',section);add('p',p.author_note,section)}}catch(e){target.textContent='Não foi possível carregar os episódios.';console.error(e)}}
run();
})();