(()=>{'use strict';const $=s=>document.querySelector(s),status=$('#creatorStatus'),workspace=$('#creatorWorkspace'),form=$('#publicationForm');let db,user;
function message(t){status.textContent=t}
function escapeText(parent,tag,text){const e=document.createElement(tag);e.textContent=text;parent.append(e);return e}
function getClient(){return typeof window.CyberUsGetClient==='function'?window.CyberUsGetClient():null}
async function refresh(){const list=$('#publicationList');list.replaceChildren();const {data,error}=await db.from('comic_publications').select('chapter_number,episode_number,language_code,title,status,publish_at').order('created_at',{ascending:false}).limit(100);if(error){escapeText(list,'p','Não foi possível carregar: '+error.message);return}if(!data.length){escapeText(list,'p','Nenhuma publicação cadastrada.');return}for(const p of data){const row=escapeText(list,'div','Cp-'+p.chapter_number+' ep-'+p.episode_number+' · '+p.language_code.toUpperCase()+' · '+p.title);row.className='creator-entry';escapeText(row,'small',p.status+(p.publish_at?' · '+new Date(p.publish_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):''))}}
async function init(){db=getClient();if(!db){message('Não foi possível inicializar a autenticação.');return}const {data:{user:u},error}=await db.auth.getUser();if(error||!u){message('Entre na sua conta antes de acessar o painel.');return}user=u;const {data:allowed,error:permissionError}=await db.rpc('cyberus_is_creator');if(permissionError){message('Painel ainda não configurado no banco. Consulte a migração do projeto.');return}if(!allowed){message('Acesso restrito ao cargo de criador.');return}workspace.hidden=false;message('Acesso autorizado.');await refresh()}
form.elements.status.addEventListener('change',()=>{$('#scheduleWrap').hidden=form.elements.status.value!=='scheduled'});
form.addEventListener('submit',async e=>{e.preventDefault();if(!db||!user)return;const f=form.elements,mode=f.status.value;let publishAt=null;if(mode==='scheduled'){if(!f.schedule.value){message('Informe data e horário.');return}publishAt=new Date(f.schedule.value+':00-03:00');if(Number.isNaN(+publishAt)||publishAt<=new Date()){message('Escolha uma data futura no horário de Brasília.');return}}if(mode==='published'&&!confirm('Publicar os metadados agora? As imagens ainda não estão configuradas.'))return;const payload={chapter_number:Number(f.chapter.value),episode_number:Number(f.episode.value),language_code:f.language.value,title:f.title.value.trim(),author_note:f.note.value,status:mode,publish_at:mode==='scheduled'?publishAt.toISOString():mode==='published'?new Date().toISOString():null,created_by:user.id};const {error}=await db.from('comic_publications').insert(payload);if(error){message('Não foi possível salvar: '+error.message);return}message('Registro salvo. A publicação no leitor depende da integração de imagens e catálogo.');form.reset();$('#scheduleWrap').hidden=true;await refresh()});
$('#refreshPublications').addEventListener('click',refresh);window.addEventListener('load',init);
})();