(()=>{'use strict';const $=s=>document.querySelector(s),status=$('#creatorStatus'),workspace=$('#creatorWorkspace'),form=$('#publicationForm');let db,user;let records=[];const BUCKET='comic-pages';
function message(t){status.textContent=t}
function escapeText(parent,tag,text){const e=document.createElement(tag);e.textContent=text;parent.append(e);return e}
function getClient(){return typeof window.CyberUsGetClient==='function'?window.CyberUsGetClient():null}
async function refresh(){const list=$('#publicationList');list.replaceChildren();const {data,error}=await db.from('comic_publications').select('id,chapter_number,episode_number,language_code,title,author_note,status,publish_at').order('created_at',{ascending:false}).limit(100);if(error){escapeText(list,'p','Não foi possível carregar: '+error.message);return}records=data;if(!data.length){escapeText(list,'p','Nenhuma publicação cadastrada.');return}for(const p of data){const row=escapeText(list,'div','Cp-'+p.chapter_number+' ep-'+p.episode_number+' · '+p.language_code.toUpperCase()+' · '+p.title);row.className='creator-entry';escapeText(row,'small',p.status+(p.publish_at?' · '+new Date(p.publish_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):''));const edit=document.createElement('button');edit.type='button';edit.textContent='Editar nota do autor';edit.addEventListener('click',()=>editNote(p));row.append(edit)}}
async function editNote(p){const note=prompt('Nota do autor (até 5000 caracteres):',p.author_note||'');if(note===null)return;if(note.length>5000){message('A nota excede 5000 caracteres.');return}const {error}=await db.from('comic_publications').update({author_note:note,updated_at:new Date().toISOString()}).eq('id',p.id);if(error){message('Falha ao editar: '+error.message);return}message('Nota do autor atualizada.');await refresh()}
async function init(){db=getClient();if(!db){message('Não foi possível inicializar a autenticação.');return}const {data:{user:u},error}=await db.auth.getUser();if(error||!u){message('Entre na sua conta antes de acessar o painel.');return}user=u;const {data:allowed,error:permissionError}=await db.rpc('cyberus_is_creator');if(permissionError){message('Painel ainda não configurado no banco. Consulte a migração do projeto.');return}if(!allowed){message('Acesso restrito ao cargo de criador.');return}workspace.hidden=false;message('Acesso autorizado.');await refresh()}
form.elements.status.addEventListener('change',()=>{$('#scheduleWrap').hidden=form.elements.status.value!=='scheduled'});
form.addEventListener('submit',async e=>{e.preventDefault();if(!db||!user)return;const f=form.elements,mode=f.status.value;let publishAt=null;if(mode==='scheduled'){if(!f.schedule.value){message('Informe data e horário.');return}publishAt=new Date(f.schedule.value+':00-03:00');if(Number.isNaN(+publishAt)||publishAt<=new Date()){message('Escolha uma data futura no horário de Brasília.');return}}const files=Array.from(f.pages.files||[]);if(mode!=='draft'&&!files.length){message('Selecione as imagens antes de publicar ou agendar.');return;}if(files.some(file=>file.size>10485760||!['image/png','image/jpeg','image/webp'].includes(file.type))){message('Use JPG, PNG ou WebP de até 10 MB por imagem.');return;}const payload={chapter_number:Number(f.chapter.value),episode_number:Number(f.episode.value),language_code:f.language.value,title:f.title.value.trim(),author_note:f.note.value,status:mode,publish_at:mode==='scheduled'?publishAt.toISOString():mode==='published'?new Date().toISOString():null,created_by:user.id};const {data:created,error}=await db.from('comic_publications').insert({...payload,status:'draft',publish_at:null}).select('id').single();if(error){message('Não foi possível salvar: '+error.message);return}const uploaded=[];for(let i=0;i<files.length;i++){const file=files[i],ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg',path=created.id+'/'+String(i+1).padStart(3,'0')+'.'+ext;message('Enviando imagem '+(i+1)+' de '+files.length+'…');const result=await db.storage.from(BUCKET).upload(path,file,{contentType:file.type,upsert:false});if(result.error){message('Falha no envio da imagem '+(i+1)+': '+result.error.message+'. Registro mantido como rascunho.');return}uploaded.push(path)}const update=await db.from('comic_publications').update({page_paths:uploaded,status:mode,publish_at:mode==='scheduled'?publishAt.toISOString():mode==='published'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',created.id);if(update.error){message('Imagens enviadas, mas publicação permaneceu em rascunho: '+update.error.message);return}message(mode==='scheduled'?'Episódio agendado com sucesso.':mode==='published'?'Episódio publicado!':'Rascunho salvo.');form.reset();$('#scheduleWrap').hidden=true;await refresh()});
$('#refreshPublications').addEventListener('click',refresh);window.addEventListener('load',init);
})();