import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=file=>readFileSync(new URL('../'+file,import.meta.url),'utf8');
const base=read('supabase/migrations/20260922120000_staff_hierarchy.sql');
const enforcement=read('supabase/migrations/20260922120100_staff_hierarchy_enforcement_appeals.sql');
const guard=read('supabase/migrations/20260922120200_staff_hierarchy_hardening.sql');
test('only one existing admin becomes immutable creator, with server-side ban-sensitive roles',()=>{
 assert.match(base,/count\(\*\).*role='admin'/);
 assert.match(base,/UPDATE community_private\.staff SET role='creator' WHERE role='admin'/);
 assert.match(base,/staff_one_creator/);
 assert.match(base,/creator_anchor/);
 assert.match(base,/staff_protect_creator/);
 assert.match(base,/Creator role is immutable/);
 assert.match(base,/staff_role\(p_user uuid\)/);
 assert.match(base,/revoked_at IS NULL/);
 assert.match(base,/my_staff_role/);
});
test('Creator alone appoints Right Hand and approves staff changes',()=>{
 for(const routine of ['staff_assign','staff_pending_requests','staff_decide_request'])assert.match(base,new RegExp('FUNCTION public\\.'+routine));
 assert.match(base,/IS DISTINCT FROM 'creator'/g);
 assert.match(base,/p_role NOT IN \('moderator','right_hand','remove'\)/);
 assert.match(base,/IF v_before='creator'/);
 assert.match(base,/staff_requests/);
 assert.match(base,/staff_request_unique_pending/);
 assert.match(base,/staff_request\(p_user_id uuid,p_kind text,p_reason text\)/);
 assert.match(base,/IS DISTINCT FROM 'right_hand'/);
 assert.match(base,/p_kind NOT IN \('grant_normal','remove_normal','ban_normal'\)/);
 assert.match(base,/status='pending'/);
 assert.match(base,/decision_note/);
});
test('normal moderators cannot ban, unban, moderate or decide appeals for staff',()=>{
 assert.match(enforcement,/v_target IS NOT NULL AND v_role<>'creator'/);
 assert.match(enforcement,/v_target='creator'/);
 assert.match(enforcement,/target_staff_role/);
 assert.match(enforcement,/Only creator can unban staff/);
 assert.match(enforcement,/Only creator moderates staff content/);
 assert.match(enforcement,/fanart_staff_comment_protection/);
 assert.match(enforcement,/fanart_staff_submission_protection/);
 assert.match(enforcement,/Creator alone decides staff appeals/);
 assert.match(guard,/moderator_can_handle/);
 assert.match(guard,/creator_ban_staff/);
 assert.match(guard,/fanart_feature_staff_protection/);
 assert.match(guard,/fanart_report_staff_protection/);
});
test('role-removal appeals remain available after revocation and only creator reviews them',()=>{
 assert.match(enforcement,/my_staff_removal/);
 assert.match(enforcement,/staff_appeal_removal/);
 assert.match(enforcement,/staff_pending_role_appeals/);
 assert.match(enforcement,/staff_decide_role_appeal/);
 assert.match(enforcement,/appeal_restore/);
 assert.match(enforcement,/UNIQUE REFERENCES community_private\.staff_actions/);
 assert.match(enforcement,/IS DISTINCT FROM 'creator'/);
});
test('new management and appeals surfaces are bilingual and isolated to their pages',()=>{
 const admin=read('moderation-hierarchy.js'),appeal=read('community-staff-appeals.js'),reader=read('reader.js');
 assert.match(reader,/moderation-hierarchy\.js/);
 assert.match(reader,/community-staff-appeals\.js/);
 assert.match(admin,/my_staff_role/);
 assert.match(admin,/staff_pending_requests/);
 assert.match(admin,/staff_decide_request/);
 assert.match(admin,/staff_pending_role_appeals/);
 assert.match(admin,/staff_decide_role_appeal/);
 assert.match(admin,/staff_request/);
 assert.match(admin,/staff_assign/);
 assert.match(appeal,/my_staff_removal/);
 assert.match(appeal,/staff_appeal_removal/);
 for(const code of [admin,appeal])assert.doesNotMatch(code,/innerHTML|service_role|sb_secret_/);
});
